### ISSUE TITLE
Kernel panic

### ISSUE THREAD

**Issue by ioito** [madd-games/glidix#1]
when i run glidix.iso you build on qemu-system-x86_64 at mac, it will occur this error below:
Initializing ACPICA...
Loading ACPI tables...
Initializing all ACPI subsystems...
Initializing all ACPI objects...
Installing power button handler...
Enumerating PCI with ACPI...
In function pciWalkCallback at src/pic.c:300
Kernel panic: failed to derive IRQ for device 0 from '_SB_.LNKD'
sorry i try upload picture, but failed.

**Comment by madd-games** [comment]
What PCI devices are attached to the system?
Attach the QEMU config file/command-line switches so that I may debug this problem.

**Comment by madd-games** [comment]
OK, it now boots but has some weird hard disk I/O issues...
