### ISSUE TITLE
What licence is this under?

### ISSUE THREAD

**Issue by violetastcs** [madd-games/glidix#2]
Hello, I have been wanting to start working on a project for a whole now (Called "AnonymOS", an OS that is centred around anonymity) and I was wondering if I could use this. So, what licence is this under? And if it is under a highly restrictive licence, can I get a licence for me to use this?

Also, you never stated how to compile it, and there is no makefile.

Thanks in advance!

**Comment by madd-games** [comment]
as stated in every source file, it is under the BSD license. all you need
to do is acknowledge the source and replicate the license statement. See
for example kernel/src/capsock.c for an example of the statement. Note that
the kernel/src/acpi directory contains a third-party library, ACPICA, by
intel. refer to its license if you intend to use this part too.

**Comment by madd-games** [comment]
I added a LICENSE file to clarify this now.

**Comment by violetastcs** [comment]
Thanks!
