### ISSUE TITLE
how to run/compile glidix

### ISSUE THREAD

**Issue by Johann150** [madd-games/glidix#5]
maybe I'm just too stupid, but how would one actually compile glidix?
This info would be nice to have in the README

**Comment by madd-games** [comment]
Hello, you first need a cross-compiler.
The easiest way to install it is to go to another directory and run:

../glidix/setup-crosstools-workspace
sudo ./install.sh

(Later, when you have a C libray, you can run 'sudo ./install-stage2.sh' to install the C++ compiler).
This puts the sysroot under /glidix.

Once you've got the cross-compiler, follow this:
http://glidix.madd-games.org/build-iso.php

(Sorry, there is no guide on installing the cross-compiler on the website yet, so i specified it here)
Post a reply if you have further issues.

**Comment by The-Jat** [comment]
How to build the cross-compiler because the link are not working which you given .
Please guide me .
