### ISSUE TITLE
Links are not working to guide on how to build cross compiler

### ISSUE THREAD

**Issue by The-Jat** [madd-games/glidix#6]
The links a looks like broken . Please guide on how to build glidix and cross compiler

**Comment by madd-games** [comment]
https://glidix.madd-games.org/Building_the_cross_compiler

https://glidix.madd-games.org/Building_the_live_iso

I'm updating the ABI right now so didn't post new links yet, but here they
are

**Comment by The-Jat** [comment]
Perfect I will try it.

गुरु, 2 मई 2019, 10:32 pm को Madd Games <notifications@github.com> ने लिखा:
