### ISSUE TITLE
not building the cross compiler 

### ISSUE THREAD

**Issue by The-Jat** [madd-games/glidix#7]
I have tried a lot but the cross compiler is not building.
the first step is worked properly of downloading the required prerequisites i.e  ../glidix/setup-crosstools-workspace --sysroot=/glidix

but when executed the next command = sudo ./install.sh
it gives error saying: Link tests are not allowed after GCC_NO_EXECUTABLES.
Makefile:9662: recipe for target 'configure-zlib' failed 
make: *** [configure-zlib] Error 1

===screenshots===
![Screenshot (5509)](https://user-images.githubusercontent.com/49841018/57142220-a2501980-6dd9-11e9-8c19-5d03bf5f123e.png)
![Screenshot (5510)](https://user-images.githubusercontent.com/49841018/57142222-a2501980-6dd9-11e9-874d-5f669603c9fd.png)

**Comment by madd-games** [comment]
If I remember correctly, the problem is with GCC (or perhaps binutils?) trying to build its own zlib. Install the zlib development packages (I see you are using Ubuntu, it's zlib-dev if I remember correctly), reconfigure the toolchian again and it should build.

**Comment by madd-games** [comment]
Anyway, soon-ish I'll have a completly new toolchain running, creating executables in Glidix's own format, and the ABI will change as a result.

**Comment by madd-games** [comment]
The trick was actually to use `--with-system-zlib`. The scripts have been updated accordingly.
