### ISSUE TITLE
Building Glidix

### ISSUE THREAD

**Issue by TheArchitectEngineer** [madd-games/glidix#8]
Hi

I built the toolchain and i am trying to build it but i got some errors. 
I got errors such as : 
`find: ‘.././../Glidix/libc/sasm’: No such file or directory` 
or
`x86_64-glidix-gcc obj/src/context.o obj/src/decoder.o obj/src/install.o obj/src/reindex.o -o libgpm.so -shared -ggdb`
`/Glidix/usr/lib/gcc/x86_64-glidix/6.2.0/../../../../x86_64-glidix/bin/ld: cannot find -lc` 

Could you take a look to the Build Log ? Thank you

[GlidixBuild.log](https://github.com/madd-games/glidix/files/10829708/GlidixBuild.log)

**Comment by madd-games** [comment]
I havent maintained this in a long time, but i think its because you have to `make libc` then install the libc in the cross-compiler's search paths. (You can run `DESTDIR=/path/to/crosscompiler/usr make install-libc`)

If there are any more problems with libraries, the same can be repeated.

**Comment by TheArchitectEngineer** [comment]
Ok, I see, but should I get a foler named SASM in the LIBC folder ? 

`find: ‘.././../Glidix/libc/sasm’: No such file or directory`

Because I got this when compiling LIBC

**Comment by madd-games** [comment]
What configure command are you using?

**Comment by TheArchitectEngineer** [comment]
`./../Glidix/configure --sysroot=/glidix `

**Comment by madd-games** [comment]
Oh I see, it looks like this is something I forgot to remove...

Inside the source directory under `libc`, create an empty directory called `sasm`. That will probably work.
